version: '3'
services:
  core:
    image: willassistant/core:master
    container_name: core
    env_file:
      ../core.env
    ports:
      - "8080:8000"
  nginx:
    build: ../nginx
    links:
      - core
    ports:
      - "80:80"
