version: '3'
services:
  core:
    image: willassistant/core:master
    container_name: core
    env_file:
      ../core.env
    ports:
      - "8080:8000"
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    # Only automatically update core W.I.L.L services
    command:
      - v2tec/watchtower core
  nginx:
    build: ../nginx
    links:
      - core
    ports:
      - "80:80"
